import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import odeint
from util.config import t, step, num_traj

from trajectory.velocity import velocity
from trajectory.init_dist import init_dist

# Distribution of initial data where q0 is an array of values generated by normal distribution
dist = init_dist()

for i in range(num_traj):
    q0 = dist[0][i]
    time = np.linspace(0, t, step)

    traj = odeint(velocity, q0, time)

    plt.plot(traj, time)

plt.show()
